# Generated by Django 5.0.1 on 2024-01-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
    ]
