# Generated by Django 5.0.1 on 2024-01-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='website_images/'),
        ),
    ]
