# Generated by Django 5.0.1 on 2024-01-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_website_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
