# Generated by Django 5.0.1 on 2024-01-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.TextField()),
                ('auteur', models.TextField()),
                ('site', models.TextField()),
                ('date', models.IntegerField()),
                ('synopsis', models.TextField()),
            ],
        ),
    ]
