# Generated by Django 5.0.1 on 2024-02-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_rename_titre_article_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
