# Generated by Django 5.0.1 on 2024-05-01 07:25

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_rename_name_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='year',
            field=models.IntegerField(validators=[article.models.year_validator]),
        ),
    ]
